#!/bin/bash

#mkdir -p ./tools/out
if [ "$2" = "seed" ]; then
    cargo build -r --features seed
else
    cargo build -r
fi

cd tools/

cargo build -r

rm in/*
rm out/*
rm batch_*
rm all_results.txt
rm cases.result

case_num=$1
if [ -z "$case_num" ]; then
    case_num=100
fi


seq -w 0 $((case_num - 1)) > seeds.txt
cargo run -r --bin gen seeds.txt

ls ./in/*.txt | sort | tail -n "$case_num" > target_cases.txt

split -l 50 -d -a 4 target_cases.txt batch_

#for infile in ./tools/in/*.txt; do
#for infile in ./in/*.txt; do
for batch in batch_*; do
(
    batch_score=0
    batch_cases=0
    batch_max_score=0
    batch_max_case=""
    batch_min_score=999999999
    batch_min_case=""
    while read infile; do
        filename=$(basename "$infile")
        #outfile="./tools/out/$filename"
        outfile="./out/$filename"

        echo "start $filename..."
        #cargo run --bin $(basename "$PWD")-a <$infile >$outfile
        /workspaces/rust/target/release/tester /workspaces/rust/target/release/ahc054-a <in/$filename >out/$filename

        lines=$(wc -l < out/$filename)

        #cd tools/
        #score=$(cargo run -r --bin vis in/$filename out/$filename | grep -o '[0-9]*' | tail -1)
        # echo "Score = $score"
        if [ $lines -ne 0 ]; then
            batch_score=$((batch_score + lines))
            batch_cases=$((batch_cases + 1))

            if [ "$lines" -gt "$batch_max_score" ]; then
                batch_max_score=$lines
                batch_max_case=$filename
            fi

            if [ "$lines" -lt "$batch_min_score" ]; then
                batch_min_score=$lines
                batch_min_case=$filename
            fi

            echo "$lines $filename" >> cases.result
        fi
    done < "$batch"

    echo "Thread finished: score=$batch_score cases=$batch_cases"
    echo "$batch_score $batch_cases $batch_max_score $batch_max_case $batch_min_score $batch_min_case" >> "$batch.result"
    #cd ../
) &
done

wait

cat batch_*.result > all_results.txt

sum_score=0
cases=0
max_score=0
max_case=""
min_score=999999999
min_case=""

while read sc c maxsc maxc minsc minc; do
    sum_score=$((sum_score + sc))
    cases=$((cases + c))

    if [ "$maxsc" -gt "$max_score" ]; then
        max_score=$maxsc
        max_case=$maxc
    fi

    if [ "$minsc" -lt "$min_score" ]; then
        min_score=$minsc
        min_case=$minc
    fi
done < all_results.txt

sort -n cases.result | head -100

echo "Sum Score = $sum_score"
echo "Case = $cases"
echo "Average Score = $((sum_score / cases))"
echo "Max Score = $max_score (Case $max_case)"
echo "Min Score = $min_score (Case $min_case)"


rm batch_* all_results.txt target_cases.txt