#!/bin/bash

ContestNumber=$1
ContestName="$ContestNumber"

strCmd="cargo"
arguments="compete new $ContestName"
Result=$(Invoke-ExternalCommand "$strCmd" "$arguments")

while [[ ! "$Result" =~ "Created" ]]; do
    echo "$Result" >&2
    sleep 0.5
    Result=$(Invoke-ExternalCommand "$strCmd" "$arguments")
done

echo "$Result" >&2

cd "$ContestName" || exit

xdg-open "https://atcoder.jp/contests/$ContestName/tasks"

sleep 0.5

echo "rust-analyzer: restart server" | xclip -selection clipboard
xdotool key Shift+Ctrl+p
xdotool key Ctrl+v
xdotool key Return

echo "s a" | xclip -selection clipboard

exec bash