#!/bin/sh

ContestNumber=$1
ContestName="abc$ContestNumber"

strCmd="cargo"
arguments="compete new $ContestName --open"
Result=$(Invoke-ExternalCommand "$strCmd" "$arguments")

while [[ ! "$Result" =~ "Created" ]]; do
    echo "$Result" >&2
    sleep 0.5
    Result=$(Invoke-ExternalCommand "$strCmd" "$arguments")
done

echo "$Result" >&2

cd "$ContestName" || exit

echo "rust-analyzer: restart server" | xclip -selection clipboard
xdotool key Shift+Ctrl+p
xdotool key Ctrl+v
xdotool key Return

sleep 0.5

# with Vim extension
xdotool key Escape
xdotool key 7 G A

# without Vim extension
xdotool key Ctrl+g
xdotool key 7
xdotool key Return
xdotool key End

echo "s a" | xclip -selection clipboard

exec bash