#!/bin/bash

ContestNumber=$1
ContestName="$ContestNumber"

strCmd="cargo"
arguments="compete new $ContestName"
Result=$(Invoke-ExternalCommand "$strCmd" "$arguments")

while [[ ! "$Result" =~ "Created" ]]; do
    echo "$Result" >&2
    sleep 0.5
    Result=$(Invoke-ExternalCommand "$strCmd" "$arguments")
done

echo "$Result" >&2

cd "$ContestName" || exit

sleep 0.5

code --goto "src/bin/c.rs:7:10"
code --goto "src/bin/d.rs:7:10"
code --goto "src/bin/e.rs:7:10"
code --goto "src/bin/f.rs:7:10"

sleep 0.5

echo "rust-analyzer: restart server" | xclip -selection clipboard
xdotool key Shift+Ctrl+p
xdotool key Ctrl+v
xdotool key Return

echo "s a" | xclip -selection clipboard

exec bash